### ISSUE TITLE
Setup instructions do not work on Linux

### ISSUE THREAD

**Issue by ntoll** [nhsd-ddce/dos-capacity-status-api#2]
I'm running Ubuntu 18.04 LTS.

**Comment by stefaniuk** [comment]
Could you include the commands you are running and the output, please?

**Comment by ntoll** [comment]
Aha... ^^^ isn't in the README. I tried to follow the setup details:

```
$ make dev-install-essential
AWS_ACCOUNT_ID_MGMT is not set
AWS_ACCOUNT_ID_NONPROD is not set
AWS_ACCOUNT_ID_PROD is not set
/bin/bash: line 4: brew: command not found
/home/ntoll/src/nhsdigital/dos-capacity-status-api/build/automation/lib/macos.mk:31: recipe for target 'dev-install-essential' failed
make: *** [dev-install-essential] Error 127
```

and 

```
$ make dev-setup 
AWS_ACCOUNT_ID_MGMT is not set
AWS_ACCOUNT_ID_NONPROD is not set
AWS_ACCOUNT_ID_PROD is not set
AWS_ACCOUNT_ID_MGMT is not set
AWS_ACCOUNT_ID_NONPROD is not set
AWS_ACCOUNT_ID_PROD is not set
sudo spctl --master-disable
[sudo] password for ntoll: 
sudo: spctl: command not found
/home/ntoll/src/nhsdigital/dos-capacity-status-api/build/automation/lib/macos.mk:217: recipe for target 'dev-disable-gatekeeper' failed
make[1]: *** [dev-disable-gatekeeper] Error 1
/home/ntoll/src/nhsdigital/dos-capacity-status-api/build/automation/lib/macos.mk:4: recipe for target 'dev-setup' failed
make: *** [dev-setup] Error 2
```

Following the instructions you paste above gets me to this (using `docker-compose` from Ubuntu's debain package):

```
$ make project-build
make docker-config
docker network create uec/dos-api/0 2> /dev/null ||:
make docker-compose-stop YML=/home/ntoll/src/nhsdigital/dos-capacity-status-api/build/docker/docker-compose.yml
docker-compose \
	--file /home/ntoll/src/nhsdigital/dos-capacity-status-api/build/docker/docker-compose.yml \
	stop
docker rm --force --volumes $(docker ps --all --quiet) 2> /dev/null ||:
ERROR: Version in "/home/ntoll/src/nhsdigital/dos-capacity-status-api/build/docker/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
/home/ntoll/src/nhsdigital/dos-capacity-status-api/build/automation/lib/docker.mk:186: recipe for target 'docker-compose-stop' failed
make[1]: *** [docker-compose-stop] Error 1
Makefile:22: recipe for target 'project-stop' failed
make: *** [project-stop] Error 2
```

**Comment by ntoll** [comment]
Looking at comments online, the version packaged with Ubuntu 18.04 is apparently "old". I'm uninstalling it and will grab the latest version, then try again.

**Comment by ntoll** [comment]
OK... installing via instructions found here appears to work: https://docs.docker.com/compose/install/

**Comment by ntoll** [comment]
OK... I got the following error message when trying to start things, but this was because I had a local copy of PostgreSQL running anyway (port binding errors)... might want to highlight that in the docs.

```
$ make project-start project-log
make docker-compose-start YML=/home/ntoll/src/nhsdigital/dos-capacity-status-api/build/docker/docker-compose.yml
make docker-config
docker-compose \
	--file /home/ntoll/src/nhsdigital/dos-capacity-status-api/build/docker/docker-compose.yml \
	up --no-build --remove-orphans --detach
docker network create uec/dos-api/0 2> /dev/null ||:
Creating api ... 
Creating dos-db ... 
Creating dos-db ... error

ERROR: for dos-db  Cannot start service db-dos: driver failed programming external connectivity on endpoint dos-db (e627bd97486ca5859f8e6a308a3624dabd28a29ac039Creating api    ... done
ind: address already in use

ERROR: for db-dos  Cannot start service db-dos: driver failed programming external connectivity on endpoint dos-db (e627bd97486ca5859f8e6a308a3624dabd28a29ac0398f2d45412453311fe875): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.
/home/ntoll/src/nhsdigital/dos-capacity-status-api/build/automation/lib/docker.mk:180: recipe for target 'docker-compose-start' failed
make[1]: *** [docker-compose-start] Error 1
Makefile:19: recipe for target 'project-start' failed
make: *** [project-start] Error 2
```

However, when it starts to run I see errors like this:

```
WARNING: Building wheel for itypes failed: [Errno 13] Permission denied: '/tmp/.cache/pip/wheels'
```

and this:

```
api       | ERROR: Exception:
api       | Traceback (most recent call last):
api       |   File "/usr/local/lib/python3.8/shutil.py", line 780, in move
api       |     os.rename(src, real_dst)
api       | OSError: [Errno 18] Cross-device link: '/tmp/pip-target-ll62og3l/lib/python/request_logging' -> '/tmp/.packages/request_logging'
api       | 
api       | During handling of the above exception, another exception occurred:
api       | 
api       | Traceback (most recent call last):
api       |   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
api       |     status = self.run(options, args)
api       |   File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 504, in run
api       |     self._handle_target_dir(
api       |   File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 561, in _handle_target_dir
api       |     shutil.move(
api       |   File "/usr/local/lib/python3.8/shutil.py", line 790, in move
api       |     copytree(src, real_dst, copy_function=copy_function,
api       |   File "/usr/local/lib/python3.8/shutil.py", line 547, in copytree
api       |     return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
api       |   File "/usr/local/lib/python3.8/shutil.py", line 449, in _copytree
api       |     os.makedirs(dst, exist_ok=dirs_exist_ok)
api       |   File "/usr/local/lib/python3.8/os.py", line 221, in makedirs
api       |     mkdir(name, mode)
api       | PermissionError: [Errno 13] Permission denied: '/tmp/.packages/request_logging'
```

I find this strange since everything under `/tmp/` should be writeable (i.e. no perm errors should occur).

Any ideas what may be the cause of this last problem..?

**Comment by stefaniuk** [comment]
Good, we made some progress. So, the other thing to check is permissions for the following directories in your Ubuntu installation:

```
~/.python/pip/cache
~/.python/pip/packages
```
Docker mounts these directories inside the container, and here is the definition used for that docker run https://github.com/nhsd-ddce/dos-capacity-status-api/blob/f305a998adb355d7887e31cf73e08bfe317fb0d9/build/automation/lib/docker.mk#L362

**Comment by stefaniuk** [comment]
All the commands should run with your UID and GID. Perhaps this error is caused due to a mismatch

`PermissionError: [Errno 13] Permission denied: '/tmp/.packages/request_logging'`

**Comment by ntoll** [comment]
OK... it turns out that `root` had ownership of my `.python` directory. Now things have started I get a new error (which results in a 500 when I point my browser at the `apidoc` endpoint:

```
api       | [2020-01-30 12:31:52 +0000] [27] [ERROR] Error handling request /apidoc/
api       | Traceback (most recent call last):
api       |   File "/tmp/.packages/django/db/backends/postgresql/base.py", line 25, in <module>
api       |     import psycopg2 as Database
api       |   File "/tmp/.packages/psycopg2/__init__.py", line 50, in <module>
api       |     from psycopg2._psycopg import (                     # noqa
api       | ModuleNotFoundError: No module named 'psycopg2._psycopg'
api       | 
api       | During handling of the above exception, another exception occurred:
api       | 
api       | Traceback (most recent call last):
api       |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
api       |     self.handle_request(listener, req, client, addr)
api       |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
api       |     respiter = self.wsgi(environ, resp.start_response)
api       |   File "/tmp/.packages/django/core/handlers/wsgi.py", line 131, in __call__
api       |     signals.request_started.send(sender=self.__class__, environ=environ)
api       |   File "/tmp/.packages/django/dispatch/dispatcher.py", line 175, in send
api       |     for receiver in self._live_receivers(sender)
api       |   File "/tmp/.packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
api       |     for receiver in self._live_receivers(sender)
api       |   File "/tmp/.packages/django/db/__init__.py", line 46, in reset_queries
api       |     for conn in connections.all():
api       |   File "/tmp/.packages/django/db/utils.py", line 222, in all
api       |     return [self[alias] for alias in self]
api       |   File "/tmp/.packages/django/db/utils.py", line 222, in <listcomp>
api       |     return [self[alias] for alias in self]
api       |   File "/tmp/.packages/django/db/utils.py", line 207, in __getitem__
api       |     backend = load_backend(db['ENGINE'])
api       |   File "/tmp/.packages/django/db/utils.py", line 111, in load_backend
api       |     return import_module('%s.base' % backend_name)
api       |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
api       |     return _bootstrap._gcd_import(name[level:], package, level)
api       |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
api       |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
api       |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
api       |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
api       |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
api       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
api       |   File "/tmp/.packages/django/db/backends/postgresql/base.py", line 29, in <module>
api       |     raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
api       | django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2._psycopg'
api       | [2020-01-30 12:31:52 +0000] [27] [ERROR] Error handling request /favicon.ico
api       | Traceback (most recent call last):
api       |   File "/tmp/.packages/django/db/backends/postgresql/base.py", line 25, in <module>
api       |     import psycopg2 as Database
api       |   File "/tmp/.packages/psycopg2/__init__.py", line 50, in <module>
api       |     from psycopg2._psycopg import (                     # noqa
api       | ModuleNotFoundError: No module named 'psycopg2._psycopg'
api       | 
api       | During handling of the above exception, another exception occurred:
api       | 
api       | Traceback (most recent call last):
api       |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
api       |     self.handle_request(listener, req, client, addr)
api       |   File "/usr/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
api       |     respiter = self.wsgi(environ, resp.start_response)
api       |   File "/tmp/.packages/django/core/handlers/wsgi.py", line 131, in __call__
api       |     signals.request_started.send(sender=self.__class__, environ=environ)
api       |   File "/tmp/.packages/django/dispatch/dispatcher.py", line 175, in send
api       |     for receiver in self._live_receivers(sender)
api       |   File "/tmp/.packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
api       |     for receiver in self._live_receivers(sender)
api       |   File "/tmp/.packages/django/db/__init__.py", line 46, in reset_queries
api       |     for conn in connections.all():
api       |   File "/tmp/.packages/django/db/utils.py", line 222, in all
api       |     return [self[alias] for alias in self]
api       |   File "/tmp/.packages/django/db/utils.py", line 222, in <listcomp>
api       |     return [self[alias] for alias in self]
api       |   File "/tmp/.packages/django/db/utils.py", line 207, in __getitem__
api       |     backend = load_backend(db['ENGINE'])
api       |   File "/tmp/.packages/django/db/utils.py", line 111, in load_backend
api       |     return import_module('%s.base' % backend_name)
api       |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
api       |     return _bootstrap._gcd_import(name[level:], package, level)
api       |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
api       |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
api       |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
api       |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
api       |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
api       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
api       |   File "/tmp/.packages/django/db/backends/postgresql/base.py", line 29, in <module>
api       |     raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
api       | django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2._psycopg'
```

Is the Python Postgresql correctly installed..?

**Comment by ntoll** [comment]
Workaround for the postgres error:

```
make api-build
api-start
```

that gets the API running over at localhost:8000

**Comment by stefaniuk** [comment]
Great news! You have it working.

Yes, the `gunicorn` enabled app has an issue with the Postgres client library. But the dev version works fine.
